---
title: "index.Rmd"
output: html_document
---

```{r, echo = FALSE, message = FALSE}
library(knitr)
library(dplyr)
library(plotly)
setwd("~/Desktop/Winter 2015-2016/info498f/INFO498F_FINAL")


bleaching <- read.csv("data/CoralBleaching.csv", stringsAsFactors = FALSE)

m <- list(
  colorbar = list(title = "Map of Coral Bleaching"),
  size = 8, opacity = 0.8, symbol = 'circle'
)

g <- list(
  showland = TRUE,
  landcolor = toRGB("gray95"),
  subunitcolor = toRGB("gray85"),
  countrycolor = toRGB("gray85"),
  countrywidth = 0.5,
  subunitwidth = 0.5
)

plot_ly(bleaching, lat = LAT, lon = LON, text = BLEACHING_SEVERITY, size = SEVERITY_CODE, color = SEVERITY_CODE, type = "scattergeo",  mode = "markers",  opacity = 0.8) %>% 
  layout(title="Coral Reef Bleaching", geo = g)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
reef_location <- read.csv("data/ReefLocations.csv", stringsAsFactors = FALSE)

m <- list(
  colorbar = list(title = "Map of Reef Locations"),
  size = 8, opacity = 0.8, symbol = 'circle'
)

g <- list(
  showland = TRUE,
  landcolor = toRGB("gray95"),
  subunitcolor = toRGB("gray85"),
  countrycolor = toRGB("gray85"),
  countrywidth = 0.5,
  subunitwidth = 0.5
)

plot_ly(reef_location, lat = LAT, lon = LON, text = REEF_NAME, type = "scattergeo",  mode = "markers",  opacity = 0.8) %>% 
  layout(title="Reef Locations", geo = g)
```


```{r, echo = FALSE, message = FALSE}
marine_protected <- read.csv("data/MarineProtectedAreas.csv", stringsAsFactors = FALSE)
m <- list(
  colorbar = list(title = "Map of Protected Areas"),
  size = 8, opacity = 0.8, symbol = 'circle'
)

g <- list(
  showland = TRUE,
  landcolor = toRGB("gray95"),
  subunitcolor = toRGB("gray85"),
  countrycolor = toRGB("gray85"),
  countrywidth = 0.5,
  subunitwidth = 0.5
)

plot_ly(marine_protected, lat = LAT, lon = LON, text = TYPE, size = REEF_AREA_SIZE,color = TYPE, type = "scattergeo",  mode = "markers",  opacity = 0.8) %>% 
  layout(title="Map of Protected Areas", geo = g)
```
